databases:
  - name: collaborativedrawingboard
    databaseName: collaborativedrawingboard
    user: collaborativedrawingboard
    plan: free

services:
  - type: web
    name: collaborativedrawingboard
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collaborativedrawingboard
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default